



net_config:
  type: models.vit.mae_gaze.MAE_Gaze
  params: 
    model_type: 'vit_b_16'
    global_pool: False
    drop_path_rate: 0.1
    custom_pretrained_path: checkpoints/vit_pretrain/face_mae_1024_vit_base_16/ablation_no_colorjitter/vit-b-16-full_no_color_jitter-299.pth