
s
net_config:
  type: models.vit.mae_gaze.MAE_Gaze
  params: 
    model_type: 'vit_l_16'
    global_pool: False
    drop_path_rate: 0.1
    custom_pretrained_path: checkpoints/mae_l16/mae_h14_checkpoint-299.pth


