



net_config:
  type: models.vit.mae_gaze.MAE_Gaze
  params: 
    model_type: 'vit_b_16'
    global_pool: False
    drop_path_rate: 0.1
    custom_pretrained_path: checkpoints/mae_b16/mae_b16_checkpoint-299.pth