



exp_name: tbd


exp_explanation: 

data: null 

## can be overwritten
model: null 


trainer:  null
loss:  null


optimizer: configs/optimizers/default_Adam_e4.yaml
scheduler: configs/schedulers/default_stepLR_5.yaml

