



exp_name: tbd


exp_explanation: 


data: null 
# configs/data/xgaze_60sub_d3.yaml
# configs/data/xgaze_60sub.yaml


## can be overwritten
model: null 
# configs/model/res50.yaml
# configs/model/vit_b_16_gaze.yaml


trainer:  null
loss:  null


optimizer: configs/optimizers/default_Adam_e4.yaml
scheduler: configs/schedulers/default_stepLR_5.yaml

