

train: 
  - configs/data/xgaze/xgaze_0_60sub_d3.yaml
  - configs/data/gazecapture_train_ds15.yaml
  - configs/data/mpiigaze_train.yaml
  - configs/data/eyediap_cs_train.yaml
  - configs/data/eyediap_ft_train.yaml
  - configs/data/gaze360_train.yaml


val: 
  - configs/data/eyediap_cs_test.yaml
  - configs/data/eyediap_ft_test.yaml
  - configs/data/gaze360_test.yaml
  - configs/data/mpiigaze_test.yaml
  - configs/data/our_mpii_test.yaml

test: 
  - configs/data/xgaze/xgaze_60_80sub.yaml
  - configs/data/gazecapture_test.yaml


