

train: 
  - configs/data/entry/xgaze/xgaze_0_60sub_d3.yaml
  - configs/data/entry/gazecapture_train_ds15.yaml
  - configs/data/entry/mpiigaze_train.yaml
  - configs/data/entry/eyediap_cs_train.yaml
  - configs/data/entry/eyediap_ft_train.yaml
  - configs/data/entry/gaze360_train.yaml


val: 
  - configs/data/entry/eyediap_cs_test.yaml
  - configs/data/entry/eyediap_ft_test.yaml
  - configs/data/entry/gaze360_test.yaml
  - configs/data/entry/mpiigaze_test.yaml
  - configs/data/entry/our_mpii_test.yaml

test: 
  - configs/data/entry/xgaze/xgaze_60_80sub.yaml
  - configs/data/entry/gazecapture_test.yaml


