


train: 
  - configs/data/entry/eyediap_cs.yaml
  - configs/data/entry/eyediap_ft.yaml



val: 
  
  - configs/data/entry/mpiigaze_train.yaml
  - configs/data/entry/mpiigaze_test.yaml
  

test: 
  # - configs/data/entry/xgaze/xgaze_0_80sub.yaml
  - configs/data/entry/xgaze/xgaze_0_60sub.yaml
  - configs/data/entry/xgaze/xgaze_60_80sub.yaml
  
  - configs/data/entry/gazecapture_train.yaml
  - configs/data/entry/gazecapture_test.yaml
  - configs/data/entry/gaze360_train.yaml
  - configs/data/entry/gaze360_test.yaml

  - configs/data/entry/mpiigaze.yaml
  - configs/data/entry/our_mpii.yaml