
train: 
  - configs/data/gazecapture_train_ds15.yaml
  - configs/data/gazecapture_test_ds15.yaml



val: 
  - configs/data/mpiigaze_train.yaml
  - configs/data/mpiigaze_test.yaml

  - configs/data/eyediap_cs_train.yaml
  - configs/data/eyediap_cs_test.yaml
  - configs/data/eyediap_ft_train.yaml
  - configs/data/eyediap_ft_test.yaml


test: 

  - configs/data/xgaze_0_60sub.yaml
  - configs/data/xgaze_60_80sub.yaml
  - configs/data/gaze360_train.yaml
  - configs/data/gaze360_test.yaml
  - configs/data/mpiigaze.yaml
  - configs/data/eyediap_cs.yaml
  - configs/data/eyediap_ft.yaml