


train: 
  - configs/data/eyediap_cs.yaml
  - configs/data/eyediap_ft.yaml



val: 
  
  - configs/data/mpiigaze_train.yaml
  - configs/data/mpiigaze_test.yaml
  

test: 
  # - configs/data/xgaze/xgaze_0_80sub.yaml
  - configs/data/xgaze/xgaze_0_60sub.yaml
  - configs/data/xgaze/xgaze_60_80sub.yaml
  
  - configs/data/gazecapture_train.yaml
  - configs/data/gazecapture_test.yaml
  - configs/data/gaze360_train.yaml
  - configs/data/gaze360_test.yaml

  - configs/data/mpiigaze.yaml
  - configs/data/our_mpii.yaml